### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Hoang-Minh** [lyndachiwetelu/using-passport-with-sequelize-and-mysql#4]
I cloned the project to my computer and tried to run it, but the signup page is not working for me at all. Can you take a look into the issue ? Thanks

**Comment by Nadia-B** [comment]
Hi, 

What kind of error do you have ?
Can you retrieve the form data ?

**Comment by Hoang-Minh** [comment]
After submitting info in the sign up page, I keep getting this error:

`Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'firstname' in 'field list'
    at Query.formatError (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query.ErrorPacket (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\Bootcamp\Practice\AnotherBasicLoginApp\PassportLogin\node_modules\mysql\lib\Connection.js:103:28)`

**Comment by Nadia-B** [comment]
Do you have a 'firstname' on your user model ?

**Comment by Hoang-Minh** [comment]
Of course i do. i clone your entire project right :)

**Comment by Nadia-B** [comment]
When you run a npm start can you see "Nice! Database looks fine" message ?
The base has been created ?

**Comment by Hoang-Minh** [comment]
yes, it does. the server is up and running correctly.
problem only arises after i submit my sign up info

**Comment by Hoang-Minh** [comment]
it's easy to reproduce the issue. Just clone the entire your project, then run npm update, after that, launch your server, then go to the sign up page, fill in info and hit submit, then you would see the problem

**Comment by Hoang-Minh** [comment]
yeah, I guess some update packages break the project
I will do as your suggestion.

Thanks for your help.

**Comment by Nadia-B** [comment]
Keep me informed !
